config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registered_applications
  namespace :api, defaults: { format: :json } do
     match '/events', to: 'events#preflight', via: [:options]
     resources :events, only: [:create]
   end
  authenticated :user do
    root 'registered_applications#index', as: :authenticated_root
  end
  root to: 'home#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  skip_before_action :authenticate_user!

   def set_access_control_headers

     headers['Access-Control-Allow-Origin'] = '*'

     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

   def create
     registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
     if registered_application.nil?
       return render json: "Unregistered application", status: :unprocessable_entity
     else
       @event = registered_application.events.new(event_params)
       if @event.save
         render json: @event, status: :created
       else
         render json: {errors: @event.errors}, status: :unprocessable_entity
       end
    end
   end

   def preflight
    head 200
   end

   private

   def event_params
     params.require(:event).permit(:name)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = current_user.registered_applications
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = current_user.registered_applications.new(registered_application_params)
    if @registered_application.save
      flash[:notice] = "Application was saved."
        redirect_to root_path

    else
      flash[:alert] = "There was an error saving your application."
        render :new
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    if @registered_application.destroy
      flash[:notice] = "Application was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the wiki."
    end
    redirect_to root_path
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url, :user)
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/views/home/index.html.erb
<h1>Welcome <%= current_user.email %></h1>

<%= link_to "View Registered Applications", registered_applications_path, class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
    - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <% if flash[:notice] %>
    <div class="alert alert-sucess">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>

    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for @registered_application do |f| %>
  <% if @registered_application.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@item.errors.count, "error")%>.</h4>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %>></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplications#create</h1>
<p>Find me in app/views/registered_applications/create.html.erb</p>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>
<div class="row">
  <div class="col-md-6">
    <% @registered_applications.each do |registered_application| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <p><%= link_to registered_application.name, registered_application %></p>
            <small>
              <%= registered_application.url %>
            </small>
          </h4>
        </div>
      </div>
      <%= link_to "Delete Application", registered_application, method: :delete, class: 'btn btn-success'%>

    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Application", new_registered_application_path, class: 'btn btn-success'%>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="row">
  <div class='col-md-4'>
    <%= render 'form', locals: { registered_application: @registered_application } %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>
<div class="row">
  <div class="col-md-4">
    <% @registered_application.events.each do |event| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <p><%= event.name %></p>

          </h4>
        </div>
      </div>
    <% end %>
    <%= pie_chart @registered_application.events.group(:name).count %>
    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
  </div>
</div>